# Generated by Django 4.0.4 on 2022-04-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_doctor_options_alter_patient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
    ]
