# Generated by Django 4.0.4 on 2022-04-23 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_alter_doctor_options_alter_patient_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consaltations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_symptoms', models.TextField()),
                ('history', models.TextField(blank=True)),
                ('x_rays_else', models.ImageField(blank=True, null=True, upload_to='')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.patient')),
            ],
        ),
    ]
