# Generated by Django 4.0.4 on 2022-04-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consaltations',
            name='category',
            field=models.CharField(default='no category', max_length=50),
        ),
        migrations.AlterField(
            model_name='consaltations',
            name='x_rays_else',
            field=models.ImageField(blank=True, upload_to='consultation_image/{patient}/'),
        ),
    ]
