# Generated by Django 4.0.4 on 2022-04-25 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_doctor_options_alter_patient_options'),
        ('pages', '0007_alter_consaltations_x_rays_else'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consaltations',
            name='category',
            field=models.ForeignKey(default='no category', on_delete=django.db.models.deletion.CASCADE, to='members.specialties'),
        ),
    ]
