# Generated by Django 4.0.4 on 2022-04-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_prescription_consult_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='re_prescription_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
