# Generated by Django 4.0.4 on 2022-04-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_prescription_re_prescription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consaltations',
            name='is_reconsult',
            field=models.BooleanField(default=False),
        ),
    ]
